### ISSUE TITLE
选择其他地区网络请求异常

### ISSUE THREAD

**Issue by ghost** [myvin/quietweather#12]
选择其他地区为什么网络不给力，要具体配哪里吗

**Comment by fthux** [comment]
@tongbil 我这里不会啊，只要参数对了的话应该没有问题的，毕竟线上跑的挺正常的，查下传的参数是否正确吧。

**Comment by ghost** [comment]
我直接打印去浏览器 抱这个  {"status":240,"message":"APP 服务被禁用"}

**Comment by fthux** [comment]
@tongbil 这种具体的问题属于 API 调用的问题了，可以直接上和风天气官网看下 API 文档，直接发请求看看，应该都是正常的。返回的错误状态码也可以查看下文档，应该都能解决的。

**Comment by ghost** [comment]
解决了 我用的是你提示的回退版本。你那个app.json 的是调用百度的api 已经过时了，我用的还是百度api  选区其他城市现在是调这个api     `https://api.map.baidu.com/geocoding/v3/?address=${address}&output=json&ak=?`
