### ISSUE TITLE
上线

### ISSUE THREAD

**Issue by WsmDyj** [myvin/quietweather#2]
你的小程序是怎么上线的呢

**Comment by myvin** [comment]
就是按照小程序上线的正常流程上线的，注明了是第三方开发的，不是官方开发，上线完全正常

**Comment by myvin** [comment]
@WsmDyj  就是按照小程序上线的正常流程上线的，注明了是第三方开发的，不是官方开发，上线完全正常

**Comment by fthux** [comment]
@WsmDyj  就是按照小程序正常流程上线的，注册小程序，配置域名白名单，提交审核上线，地图的话需要在开放平台注册获取个 key
