### ISSUE TITLE
工具未校验合法域名、web-view（业务域名）、TLS 版本以及 HTTPS 证书。

### ISSUE THREAD

**Issue by JhonLee-Up** [myvin/quietweather#3]
工具未校验合法域名、web-view（业务域名）、TLS 版本以及 HTTPS 证书。（麻烦回答一下原因）

**Comment by fthux** [comment]
@GodLiyf  在使用开发工具进行开发的时候，如果选择校验域名、证书、版本时，业务域名、请求域名都需要在后台添加白名单，否则会报错，小程序无法正常运行；如果选择不校验的话，就是完全的开发环境，均不会报错。

**Comment by fthux** [comment]
@GodLiyf  这属于小程序开发的基础知识，还是建议看下官方文档哈~~~~~~~
