### ISSUE TITLE
关于UI的疑问

### ISSUE THREAD

**Issue by liuqiuhua1** [myvin/quietweather#4]
小程序的页面好漂亮，想问一下作者是不是懂UI设计的，这些页面的设计稿和图标是作者自己弄的吗，我想开发自己的项目，但是不懂UI设计，页面编写无从下手

**Comment by fthux** [comment]
@LQH1994 我不懂 UI 的，哈哈，没有设计稿、没有自己绘制图标，手机上那么多 APP，多看几个，借鉴借鉴，就出来了，图标都是从网上找的

**Comment by fthux** [comment]
@LQH1994 可以直接在纸上简单手画，脑子里有设计就行，然后在页面上实现个大概，然后慢慢调，我不懂 UI，所以这都是个人意见哈~~~

**Comment by mrpsweet** [comment]
大哥 和风天气  一直报app不存在、ak有误

**Comment by fthux** [comment]
@mrpsweet 这种问题还是得自己检查核实一下吧，应该不会难

**Comment by mrpsweet** [comment]
谢谢你

**Comment by fthux** [comment]
@mrpsweet 不客气的~
