### ISSUE TITLE
云开发的数据库疑问

### ISSUE THREAD

**Issue by java2ming** [myvin/quietweather#5]
请问下：数据库broadcast里面格式是什么样的？获取数据的时候为空

**Comment by myvin** [comment]
有 24 个 record，每个 record 的字段有：hour、message，hour 从 0 - 23，总共 24 个小时，eg：
"hour": 6
"message": 早上好，这么早就醒了，住的离公司远了吧

**Comment by fthux** [comment]
@java2ming 有 24 个 record，每个 record 的字段有：hour、message，hour 从 0 - 23，总共 24 个小时，eg：
"hour": 6
"message": 早上好，这么早就醒了，住的离公司远了吧

**Comment by fthux** [comment]
@java2ming 可以直接注释掉，或者在云函数里面直接返回内容，不用读取数据库

**Comment by java2ming** [comment]
@myvin  谢谢，了解了。

**Comment by fthux** [comment]
@java2ming 恩恩，客气了
